### ISSUE TITLE
incorrect install instructions for linux re lpsolve location

### ISSUE THREAD

**Issue by gaffo** [draffensperger/golp#1]
Your instructions in the readme say that it should be in lib/lpsolve but the lp.go actually says ./lpsolve. Which is it?

Also when you say "Project" I'm not sure where you want that to be... is that $GOPATH? or is that the code Im using to use lpsolve, or is it actualy in $GOPATH/src/github.com/draffenspeerger/golp/lpsolve?

**Comment by gaffo** [comment]
it looks like it's the last one for linux. I'm just going to submit a patch to the readme and reference this.

**Comment by draffensperger** [comment]
Fixed by @gaffo here: https://github.com/draffensperger/golp/pull/2
