### ISSUE TITLE
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in

### ISSUE THREAD

**Issue by gandaldf** [draffensperger/golp#11]
Hi I'm trying to use your package on Windows and I get this message while I'm trying to compile the basic example on README.md:
```
# github.com/draffensperger/golp
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in
```
Is there something I can do to make it works?

Thank you!

**Comment by draffensperger** [comment]
Does this help at all? https://stackoverflow.com/questions/39863157/cgo-sorry-unimplemented-64-bit-mode-not-compiled-in

I'm definitely open to PRs that would improve this repo for Windows.
